/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MerchantRouteImport } from './routes/merchant'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as LibraryImportRouteImport } from './routes/library-import'
import { Route as HomeRouteImport } from './routes/home'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as CreditRouteImport } from './routes/credit'
import { Route as ChooseRoleRouteImport } from './routes/choose-role'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MerchantIndexRouteImport } from './routes/merchant.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StoreStoreIdRouteImport } from './routes/store.$storeId'
import { Route as MerchantSettingsRouteImport } from './routes/merchant.settings'
import { Route as MerchantReturnsRouteImport } from './routes/merchant.returns'
import { Route as MerchantReportsRouteImport } from './routes/merchant.reports'
import { Route as MerchantProductsRouteImport } from './routes/merchant.products'
import { Route as MerchantPosRouteImport } from './routes/merchant.pos'
import { Route as MerchantOrdersRouteImport } from './routes/merchant.orders'
import { Route as MerchantCreditRouteImport } from './routes/merchant.credit'
import { Route as AdminWalletsRouteImport } from './routes/admin.wallets'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTeamRouteImport } from './routes/admin.team'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminMerchantsRouteImport } from './routes/admin.merchants'
import { Route as AdminLibraryRouteImport } from './routes/admin.library'
import { Route as AdminKpisRouteImport } from './routes/admin.kpis'
import { Route as AdminBroadcastRouteImport } from './routes/admin.broadcast'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as ApiSbSplatRouteImport } from './routes/api/sb.$'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRoute = MerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryImportRoute = LibraryImportRouteImport.update({
  id: '/library-import',
  path: '/library-import',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditRoute = CreditRouteImport.update({
  id: '/credit',
  path: '/credit',
  getParentRoute: () => rootRouteImport,
} as any)
const ChooseRoleRoute = ChooseRoleRouteImport.update({
  id: '/choose-role',
  path: '/choose-role',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantIndexRoute = MerchantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MerchantRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StoreStoreIdRoute = StoreStoreIdRouteImport.update({
  id: '/store/$storeId',
  path: '/store/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantSettingsRoute = MerchantSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantReturnsRoute = MerchantReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantReportsRoute = MerchantReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantProductsRoute = MerchantProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantPosRoute = MerchantPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantOrdersRoute = MerchantOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantCreditRoute = MerchantCreditRouteImport.update({
  id: '/credit',
  path: '/credit',
  getParentRoute: () => MerchantRoute,
} as any)
const AdminWalletsRoute = AdminWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMerchantsRoute = AdminMerchantsRouteImport.update({
  id: '/merchants',
  path: '/merchants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLibraryRoute = AdminLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKpisRoute = AdminKpisRouteImport.update({
  id: '/kpis',
  path: '/kpis',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBroadcastRoute = AdminBroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const ApiSbSplatRoute = ApiSbSplatRouteImport.update({
  id: '/api/sb/$',
  path: '/api/sb/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/choose-role': typeof ChooseRoleRoute
  '/credit': typeof CreditRoute
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/library-import': typeof LibraryImportRoute
  '/locations': typeof LocationsRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/wallet': typeof WalletRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/kpis': typeof AdminKpisRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/merchant/credit': typeof MerchantCreditRoute
  '/merchant/orders': typeof MerchantOrdersRoute
  '/merchant/pos': typeof MerchantPosRoute
  '/merchant/products': typeof MerchantProductsRoute
  '/merchant/reports': typeof MerchantReportsRoute
  '/merchant/returns': typeof MerchantReturnsRoute
  '/merchant/settings': typeof MerchantSettingsRoute
  '/store/$storeId': typeof StoreStoreIdRoute
  '/admin/': typeof AdminIndexRoute
  '/merchant/': typeof MerchantIndexRoute
  '/api/sb/$': typeof ApiSbSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/choose-role': typeof ChooseRoleRoute
  '/credit': typeof CreditRoute
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/library-import': typeof LibraryImportRoute
  '/locations': typeof LocationsRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/wallet': typeof WalletRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/kpis': typeof AdminKpisRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/merchant/credit': typeof MerchantCreditRoute
  '/merchant/orders': typeof MerchantOrdersRoute
  '/merchant/pos': typeof MerchantPosRoute
  '/merchant/products': typeof MerchantProductsRoute
  '/merchant/reports': typeof MerchantReportsRoute
  '/merchant/returns': typeof MerchantReturnsRoute
  '/merchant/settings': typeof MerchantSettingsRoute
  '/store/$storeId': typeof StoreStoreIdRoute
  '/admin': typeof AdminIndexRoute
  '/merchant': typeof MerchantIndexRoute
  '/api/sb/$': typeof ApiSbSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/choose-role': typeof ChooseRoleRoute
  '/credit': typeof CreditRoute
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/library-import': typeof LibraryImportRoute
  '/locations': typeof LocationsRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/wallet': typeof WalletRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/kpis': typeof AdminKpisRoute
  '/admin/library': typeof AdminLibraryRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/merchant/credit': typeof MerchantCreditRoute
  '/merchant/orders': typeof MerchantOrdersRoute
  '/merchant/pos': typeof MerchantPosRoute
  '/merchant/products': typeof MerchantProductsRoute
  '/merchant/reports': typeof MerchantReportsRoute
  '/merchant/returns': typeof MerchantReturnsRoute
  '/merchant/settings': typeof MerchantSettingsRoute
  '/store/$storeId': typeof StoreStoreIdRoute
  '/admin/': typeof AdminIndexRoute
  '/merchant/': typeof MerchantIndexRoute
  '/api/sb/$': typeof ApiSbSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/choose-role'
    | '/credit'
    | '/favorites'
    | '/home'
    | '/library-import'
    | '/locations'
    | '/merchant'
    | '/notifications'
    | '/orders'
    | '/profile'
    | '/wallet'
    | '/admin/analytics'
    | '/admin/banners'
    | '/admin/broadcast'
    | '/admin/kpis'
    | '/admin/library'
    | '/admin/merchants'
    | '/admin/orders'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/users'
    | '/admin/wallets'
    | '/merchant/credit'
    | '/merchant/orders'
    | '/merchant/pos'
    | '/merchant/products'
    | '/merchant/reports'
    | '/merchant/returns'
    | '/merchant/settings'
    | '/store/$storeId'
    | '/admin/'
    | '/merchant/'
    | '/api/sb/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cart'
    | '/choose-role'
    | '/credit'
    | '/favorites'
    | '/home'
    | '/library-import'
    | '/locations'
    | '/notifications'
    | '/orders'
    | '/profile'
    | '/wallet'
    | '/admin/analytics'
    | '/admin/banners'
    | '/admin/broadcast'
    | '/admin/kpis'
    | '/admin/library'
    | '/admin/merchants'
    | '/admin/orders'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/users'
    | '/admin/wallets'
    | '/merchant/credit'
    | '/merchant/orders'
    | '/merchant/pos'
    | '/merchant/products'
    | '/merchant/reports'
    | '/merchant/returns'
    | '/merchant/settings'
    | '/store/$storeId'
    | '/admin'
    | '/merchant'
    | '/api/sb/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/choose-role'
    | '/credit'
    | '/favorites'
    | '/home'
    | '/library-import'
    | '/locations'
    | '/merchant'
    | '/notifications'
    | '/orders'
    | '/profile'
    | '/wallet'
    | '/admin/analytics'
    | '/admin/banners'
    | '/admin/broadcast'
    | '/admin/kpis'
    | '/admin/library'
    | '/admin/merchants'
    | '/admin/orders'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/users'
    | '/admin/wallets'
    | '/merchant/credit'
    | '/merchant/orders'
    | '/merchant/pos'
    | '/merchant/products'
    | '/merchant/reports'
    | '/merchant/returns'
    | '/merchant/settings'
    | '/store/$storeId'
    | '/admin/'
    | '/merchant/'
    | '/api/sb/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  ChooseRoleRoute: typeof ChooseRoleRoute
  CreditRoute: typeof CreditRoute
  FavoritesRoute: typeof FavoritesRoute
  HomeRoute: typeof HomeRoute
  LibraryImportRoute: typeof LibraryImportRoute
  LocationsRoute: typeof LocationsRoute
  MerchantRoute: typeof MerchantRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  OrdersRoute: typeof OrdersRoute
  ProfileRoute: typeof ProfileRoute
  WalletRoute: typeof WalletRoute
  StoreStoreIdRoute: typeof StoreStoreIdRoute
  ApiSbSplatRoute: typeof ApiSbSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library-import': {
      id: '/library-import'
      path: '/library-import'
      fullPath: '/library-import'
      preLoaderRoute: typeof LibraryImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit': {
      id: '/credit'
      path: '/credit'
      fullPath: '/credit'
      preLoaderRoute: typeof CreditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/choose-role': {
      id: '/choose-role'
      path: '/choose-role'
      fullPath: '/choose-role'
      preLoaderRoute: typeof ChooseRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/': {
      id: '/merchant/'
      path: '/'
      fullPath: '/merchant/'
      preLoaderRoute: typeof MerchantIndexRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/store/$storeId': {
      id: '/store/$storeId'
      path: '/store/$storeId'
      fullPath: '/store/$storeId'
      preLoaderRoute: typeof StoreStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/settings': {
      id: '/merchant/settings'
      path: '/settings'
      fullPath: '/merchant/settings'
      preLoaderRoute: typeof MerchantSettingsRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/returns': {
      id: '/merchant/returns'
      path: '/returns'
      fullPath: '/merchant/returns'
      preLoaderRoute: typeof MerchantReturnsRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/reports': {
      id: '/merchant/reports'
      path: '/reports'
      fullPath: '/merchant/reports'
      preLoaderRoute: typeof MerchantReportsRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/products': {
      id: '/merchant/products'
      path: '/products'
      fullPath: '/merchant/products'
      preLoaderRoute: typeof MerchantProductsRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/pos': {
      id: '/merchant/pos'
      path: '/pos'
      fullPath: '/merchant/pos'
      preLoaderRoute: typeof MerchantPosRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/orders': {
      id: '/merchant/orders'
      path: '/orders'
      fullPath: '/merchant/orders'
      preLoaderRoute: typeof MerchantOrdersRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/credit': {
      id: '/merchant/credit'
      path: '/credit'
      fullPath: '/merchant/credit'
      preLoaderRoute: typeof MerchantCreditRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/admin/wallets': {
      id: '/admin/wallets'
      path: '/wallets'
      fullPath: '/admin/wallets'
      preLoaderRoute: typeof AdminWalletsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/merchants': {
      id: '/admin/merchants'
      path: '/merchants'
      fullPath: '/admin/merchants'
      preLoaderRoute: typeof AdminMerchantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/library': {
      id: '/admin/library'
      path: '/library'
      fullPath: '/admin/library'
      preLoaderRoute: typeof AdminLibraryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kpis': {
      id: '/admin/kpis'
      path: '/kpis'
      fullPath: '/admin/kpis'
      preLoaderRoute: typeof AdminKpisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/broadcast': {
      id: '/admin/broadcast'
      path: '/broadcast'
      fullPath: '/admin/broadcast'
      preLoaderRoute: typeof AdminBroadcastRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/sb/$': {
      id: '/api/sb/$'
      path: '/api/sb/$'
      fullPath: '/api/sb/$'
      preLoaderRoute: typeof ApiSbSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminBroadcastRoute: typeof AdminBroadcastRoute
  AdminKpisRoute: typeof AdminKpisRoute
  AdminLibraryRoute: typeof AdminLibraryRoute
  AdminMerchantsRoute: typeof AdminMerchantsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWalletsRoute: typeof AdminWalletsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminBroadcastRoute: AdminBroadcastRoute,
  AdminKpisRoute: AdminKpisRoute,
  AdminLibraryRoute: AdminLibraryRoute,
  AdminMerchantsRoute: AdminMerchantsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWalletsRoute: AdminWalletsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MerchantRouteChildren {
  MerchantCreditRoute: typeof MerchantCreditRoute
  MerchantOrdersRoute: typeof MerchantOrdersRoute
  MerchantPosRoute: typeof MerchantPosRoute
  MerchantProductsRoute: typeof MerchantProductsRoute
  MerchantReportsRoute: typeof MerchantReportsRoute
  MerchantReturnsRoute: typeof MerchantReturnsRoute
  MerchantSettingsRoute: typeof MerchantSettingsRoute
  MerchantIndexRoute: typeof MerchantIndexRoute
}

const MerchantRouteChildren: MerchantRouteChildren = {
  MerchantCreditRoute: MerchantCreditRoute,
  MerchantOrdersRoute: MerchantOrdersRoute,
  MerchantPosRoute: MerchantPosRoute,
  MerchantProductsRoute: MerchantProductsRoute,
  MerchantReportsRoute: MerchantReportsRoute,
  MerchantReturnsRoute: MerchantReturnsRoute,
  MerchantSettingsRoute: MerchantSettingsRoute,
  MerchantIndexRoute: MerchantIndexRoute,
}

const MerchantRouteWithChildren = MerchantRoute._addFileChildren(
  MerchantRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  ChooseRoleRoute: ChooseRoleRoute,
  CreditRoute: CreditRoute,
  FavoritesRoute: FavoritesRoute,
  HomeRoute: HomeRoute,
  LibraryImportRoute: LibraryImportRoute,
  LocationsRoute: LocationsRoute,
  MerchantRoute: MerchantRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  OrdersRoute: OrdersRoute,
  ProfileRoute: ProfileRoute,
  WalletRoute: WalletRoute,
  StoreStoreIdRoute: StoreStoreIdRoute,
  ApiSbSplatRoute: ApiSbSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
