/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MerchantRouteImport } from './routes/merchant'
import { Route as HomeRouteImport } from './routes/home'
import { Route as CreditRouteImport } from './routes/credit'
import { Route as ChooseRoleRouteImport } from './routes/choose-role'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MerchantIndexRouteImport } from './routes/merchant.index'
import { Route as StoreStoreIdRouteImport } from './routes/store.$storeId'
import { Route as MerchantSettingsRouteImport } from './routes/merchant.settings'
import { Route as MerchantProductsRouteImport } from './routes/merchant.products'
import { Route as MerchantOrdersRouteImport } from './routes/merchant.orders'
import { Route as MerchantCreditRouteImport } from './routes/merchant.credit'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRoute = MerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditRoute = CreditRouteImport.update({
  id: '/credit',
  path: '/credit',
  getParentRoute: () => rootRouteImport,
} as any)
const ChooseRoleRoute = ChooseRoleRouteImport.update({
  id: '/choose-role',
  path: '/choose-role',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantIndexRoute = MerchantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MerchantRoute,
} as any)
const StoreStoreIdRoute = StoreStoreIdRouteImport.update({
  id: '/store/$storeId',
  path: '/store/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantSettingsRoute = MerchantSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantProductsRoute = MerchantProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantOrdersRoute = MerchantOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantCreditRoute = MerchantCreditRouteImport.update({
  id: '/credit',
  path: '/credit',
  getParentRoute: () => MerchantRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/choose-role': typeof ChooseRoleRoute
  '/credit': typeof CreditRoute
  '/home': typeof HomeRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/merchant/credit': typeof MerchantCreditRoute
  '/merchant/orders': typeof MerchantOrdersRoute
  '/merchant/products': typeof MerchantProductsRoute
  '/merchant/settings': typeof MerchantSettingsRoute
  '/store/$storeId': typeof StoreStoreIdRoute
  '/merchant/': typeof MerchantIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/choose-role': typeof ChooseRoleRoute
  '/credit': typeof CreditRoute
  '/home': typeof HomeRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/merchant/credit': typeof MerchantCreditRoute
  '/merchant/orders': typeof MerchantOrdersRoute
  '/merchant/products': typeof MerchantProductsRoute
  '/merchant/settings': typeof MerchantSettingsRoute
  '/store/$storeId': typeof StoreStoreIdRoute
  '/merchant': typeof MerchantIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/choose-role': typeof ChooseRoleRoute
  '/credit': typeof CreditRoute
  '/home': typeof HomeRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/merchant/credit': typeof MerchantCreditRoute
  '/merchant/orders': typeof MerchantOrdersRoute
  '/merchant/products': typeof MerchantProductsRoute
  '/merchant/settings': typeof MerchantSettingsRoute
  '/store/$storeId': typeof StoreStoreIdRoute
  '/merchant/': typeof MerchantIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cart'
    | '/choose-role'
    | '/credit'
    | '/home'
    | '/merchant'
    | '/orders'
    | '/profile'
    | '/merchant/credit'
    | '/merchant/orders'
    | '/merchant/products'
    | '/merchant/settings'
    | '/store/$storeId'
    | '/merchant/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cart'
    | '/choose-role'
    | '/credit'
    | '/home'
    | '/orders'
    | '/profile'
    | '/merchant/credit'
    | '/merchant/orders'
    | '/merchant/products'
    | '/merchant/settings'
    | '/store/$storeId'
    | '/merchant'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/cart'
    | '/choose-role'
    | '/credit'
    | '/home'
    | '/merchant'
    | '/orders'
    | '/profile'
    | '/merchant/credit'
    | '/merchant/orders'
    | '/merchant/products'
    | '/merchant/settings'
    | '/store/$storeId'
    | '/merchant/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  ChooseRoleRoute: typeof ChooseRoleRoute
  CreditRoute: typeof CreditRoute
  HomeRoute: typeof HomeRoute
  MerchantRoute: typeof MerchantRouteWithChildren
  OrdersRoute: typeof OrdersRoute
  ProfileRoute: typeof ProfileRoute
  StoreStoreIdRoute: typeof StoreStoreIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit': {
      id: '/credit'
      path: '/credit'
      fullPath: '/credit'
      preLoaderRoute: typeof CreditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/choose-role': {
      id: '/choose-role'
      path: '/choose-role'
      fullPath: '/choose-role'
      preLoaderRoute: typeof ChooseRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/': {
      id: '/merchant/'
      path: '/'
      fullPath: '/merchant/'
      preLoaderRoute: typeof MerchantIndexRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/store/$storeId': {
      id: '/store/$storeId'
      path: '/store/$storeId'
      fullPath: '/store/$storeId'
      preLoaderRoute: typeof StoreStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/settings': {
      id: '/merchant/settings'
      path: '/settings'
      fullPath: '/merchant/settings'
      preLoaderRoute: typeof MerchantSettingsRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/products': {
      id: '/merchant/products'
      path: '/products'
      fullPath: '/merchant/products'
      preLoaderRoute: typeof MerchantProductsRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/orders': {
      id: '/merchant/orders'
      path: '/orders'
      fullPath: '/merchant/orders'
      preLoaderRoute: typeof MerchantOrdersRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/credit': {
      id: '/merchant/credit'
      path: '/credit'
      fullPath: '/merchant/credit'
      preLoaderRoute: typeof MerchantCreditRouteImport
      parentRoute: typeof MerchantRoute
    }
  }
}

interface MerchantRouteChildren {
  MerchantCreditRoute: typeof MerchantCreditRoute
  MerchantOrdersRoute: typeof MerchantOrdersRoute
  MerchantProductsRoute: typeof MerchantProductsRoute
  MerchantSettingsRoute: typeof MerchantSettingsRoute
  MerchantIndexRoute: typeof MerchantIndexRoute
}

const MerchantRouteChildren: MerchantRouteChildren = {
  MerchantCreditRoute: MerchantCreditRoute,
  MerchantOrdersRoute: MerchantOrdersRoute,
  MerchantProductsRoute: MerchantProductsRoute,
  MerchantSettingsRoute: MerchantSettingsRoute,
  MerchantIndexRoute: MerchantIndexRoute,
}

const MerchantRouteWithChildren = MerchantRoute._addFileChildren(
  MerchantRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  ChooseRoleRoute: ChooseRoleRoute,
  CreditRoute: CreditRoute,
  HomeRoute: HomeRoute,
  MerchantRoute: MerchantRouteWithChildren,
  OrdersRoute: OrdersRoute,
  ProfileRoute: ProfileRoute,
  StoreStoreIdRoute: StoreStoreIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
